### ISSUE TITLE
FindAllProjectsOnWorkspaceAsync should be aligned to clockify api

### ISSUE THREAD

**Issue by khaelys** [Morasiu/Clockify.Net#11]
`GET /workspaces/{workspaceId}/projects ` has a richer API, with lots of filters.

![image](https://user-images.githubusercontent.com/26967519/86360228-5a918000-bc72-11ea-915e-1889f750daa4.png)

It will be nice to add these filters to FindAllProjectsOnWorkspaceAsync method.

**Comment by GEPatSeeker** [comment]
Maybe this should be a separate issue, but I've noticed `ProjectRequest` and 'ProjectDtoImpl' are missing the `Notes` field

**Comment by Morasiu** [comment]
Partially fixed in #13

**Comment by Morasiu** [comment]
Nevermind.
