### ISSUE TITLE
ProjectRequest and ProjectDtoImpl are missing the Note field

### ISSUE THREAD

**Issue by GEPatSeeker** [Morasiu/Clockify.Net#13]
Maybe this should be a separate issue, but I've noticed `ProjectRequest` and `ProjectDtoImpl` are missing the `Note` field

_Originally posted by @GEPatSeeker in https://github.com/Morasiu/Clockify.Net/issues/11#issuecomment-653082056_

**Comment by GEPatSeeker** [comment]
I'm happy to add this.
@Morasiu have you had any luck fixing `Estimate`?

**Comment by Morasiu** [comment]
This looks like an easy to fix problem.

Estimate is working on develop. I'm just out of time and will probably release new version soon (Saturday)

**Comment by GEPatSeeker** [comment]
Notes added, along with relevant test

**Comment by Morasiu** [comment]
Fixes in PR #15
