### ISSUE TITLE
Test errors as Workspaces can no longer be deleted by API

### ISSUE THREAD

**Issue by GEPatSeeker** [Morasiu/Clockify.Net#14]
Due to an API change it appears workspaces can no longer be deleted via the API, as such a `workspace` generated by tests has to be manually deleted before tests can be re-run.
I suggest running all tests in a single `workspace` and use `uuid` to avoid name conflicts.
I'm unclear how to best approach the `CreateWorkspace_ShouldCreateWorkspace` test as if a `uuid` is used for `name`, re-running tests will keep adding more workspaces which will then need to be manually deleted.

**Comment by Morasiu** [comment]
That's very good sugestion. I'll change all tests to support one workplace only.

**Comment by GEPatSeeker** [comment]
Single workspace is now used. I haven't touched Cleanup

**Comment by Morasiu** [comment]
That one was fixed in #15 Good job 👍
