### ISSUE TITLE
Get time from user for specific client

### ISSUE THREAD

**Issue by targor** [Morasiu/Clockify.Net#18]
-You you add the functionality to get all times from a user for a specific client?
~~-Also, could you add the variable clientid/client_name to the TimeEntryDtoImpl?~~

**Comment by Morasiu** [comment]
Hm... I'll check that

**Comment by andrewperis** [comment]
Looks like Client is at the Project level. I'm thinking about the following logic. Thoughts?
1. Query for all Projects on Workspace filtered by provided Client.
2. Query for all User time entries on Workspace for each Project returned above.

**Comment by Morasiu** [comment]
First of all, your suggestion looks viable. That's a good strategy to approach this problem, but...

I think that one sounds like a feature request for Clockify. 

We can make but in my opinion, we should use that library just to reflect some real API endpoints and logic. 

To sum up:
If someone wants this feel free to make a feature request for Clockify (they are very nice, trust me 😉) and if they make such an endpoint or query parameter we can include this in `Clockify.Net`

I hope that's ok.

**Comment by andrewperis** [comment]
Ah yes, that makes sense to me. Thanks for sharing.

**Comment by andrewperis** [comment]
I submitted a feature request with Clockify, ticket 52429. I'll keep you posted.

**Comment by andrewperis** [comment]
The Clockify support team recommends using the Detailed Report API to achieve this request, so there's no work for them to implement. Adding support for the Report APIs was actually something I wanted to implement because I have a need for them. I'll start working on those and report back when this request is supported in Clockify.Net.

**Comment by Morasiu** [comment]
Roger that!

**Comment by andrewperis** [comment]
See PR #51 .

**Comment by Morasiu** [comment]
Done in 1.11.0

Thanks @andrewperis
