### ISSUE TITLE
Find all time entries for user in a project

### ISSUE THREAD

**Issue by stefan99x** [Morasiu/Clockify.Net#22]
-> Ability to find all the time entries in the project for a user. The project can be identified by its id. And also to add the ability to filter by different parameters.

**Comment by andrewperis** [comment]
@Morasiu looks like this request is fulfilled by FindAllTimeEntriesForUserAsync(). Is anything else missing?

**Comment by Morasiu** [comment]
Oh... It is. There is a argument called `string project`. So I guess it is done already. Nice catch. Thanks!
