### ISSUE TITLE
Add user to workspace

### ISSUE THREAD

**Issue by adriensamel** [Morasiu/Clockify.Net#24]
-> Ability to add a new user to a workspace. The newly added user will receive an invitation via email to join the workspace.

**Comment by andrewperis** [comment]
@Morasiu where would you like to see the new endpoint supported, under User or Workspace?

**Comment by Morasiu** [comment]
Probably under Workspace since it's at URL `POST /workspaces/{workspaceId}/users`

**Comment by andrewperis** [comment]
Okay, that's what I was leaning towards. Thank you for the feedback!

**Comment by Morasiu** [comment]
DONE in version 1.10.0
