### ISSUE TITLE
Bug Issue : Test failing first time. Type: Minor

### ISSUE THREAD

**Issue by stefan99x** [Morasiu/Clockify.Net#26]
*Summary*:
Some tests are are failing on the first run of the test. But after rerunning them they will pass.

*Steps to repoduce*:
Run all the tests. After they finnish run only the tests that didn't pass.

*Expected Result*:
Test to pass.

*Actual Result*:
Test are failing. And for them to pass they need to be rerun.

![bug-Issue](https://user-images.githubusercontent.com/45366875/96966434-761ce100-1516-11eb-8020-6006bb1fdf84.gif)

**Comment by Morasiu** [comment]
I've found the source of this bug. After you have 50 projects in one workspace, new workspaces don't appear in simple `FindAllProjectsOnWorkspaceAsync`. 

It is because page size is set to **50**. 

The solution would be to delete just created project after each test.

**Comment by stefan99x** [comment]
I could do that later today.

**Comment by Morasiu** [comment]
I've done it ;)
