### ISSUE TITLE
Remove package dependecies to CodeQuality

### ISSUE THREAD

**Issue by h3tz** [Morasiu/Clockify.Net#3]
Getting the project via nuget a lot of different packages will be installed in addition and results in time consuming uninstall and fixing things.

Remove CodeAnalysis and every other QA stuff (if possible) to have a smoother startup after nuget installation.

**Comment by Morasiu** [comment]
Great suggestion. Will do ;)

**Comment by Morasiu** [comment]
FIxed in 1.1.0
