### ISSUE TITLE
FindAllUsersOnWorkspace - Error UserStatus conversion

### ISSUE THREAD

**Issue by pavelrybar** [Morasiu/Clockify.Net#38]
When calling Client.FindAllUsersOnWorkspaceAsync(workspaceId, page, pagesize) this error occurs:

> Error converting value "PENDING_EMAIL_VERIFICATION" to type 'System.Nullable`1[Clockify.Net.Models.Users.UserStatus]'. Path '[18].status', line 1, position 33978.

The raw Content in the RestResponse.Content seams OK. Similar error with other user statuses different from "ACTIVE"

Using NuGet version 1.8.0

**Comment by Morasiu** [comment]
Should be fixed in 1.8.1 now
