### ISSUE TITLE
FindAllTimeEntriesForUserAsync - Support `tags: string[]` parameter

### ISSUE THREAD

**Issue by NecatiMeral** [Morasiu/Clockify.Net#39]
Hi,

thanks for your implementation of the clockify client.
I was trying to implement a redmine bridge which filters entries by a `to-redmine` tag and processes them.
Unfortunately the client doesn't implement the `tags` parameter yet (https://clockify.me/developers-api#tag-Time-entry).

**Comment by Morasiu** [comment]
Done in version 1.10.0

Thanks @andrewperis
