### ISSUE TITLE
HourlyRate.Amount from API is always 0

### ISSUE THREAD

**Issue by imflitch** [Morasiu/Clockify.Net#42]
The hourly rate is wrong in every function and the duration is also wrong.
Using for example FindAllHydratedTimeEntriesForUserAsync.

**Comment by Morasiu** [comment]
Hey, thanks for the feedback!

Could you elaborate a little?

What do you mean by "is wrong"? Like a model class in the project is different from the model in Clockify API?

**Comment by imflitch** [comment]
Hi.
The hourly rate is xx on Clockify but on the api its 0 always.

man. 5. jul. 2021 kl. 09.21 skrev Hubert Morawski ***@***.***

**Comment by Morasiu** [comment]
xx? It's `int` in the model in that library

**Comment by imflitch** [comment]
That’s not what i mean, sorry.
When i output xxxx.hourlyrate.amount its always 0 but is set to xxx on
Clockify.

man. 5. jul. 2021 kl. 11.07 skrev Hubert Morawski ***@***.***

**Comment by Morasiu** [comment]
So it's not mapping properly from Clockify to the library model?

**Comment by imflitch** [comment]
Idk, i guess yea.

For this example, i have set the hourly rate to 80 but all of them are 0 and then the total salary is calculated with the sum of the timeentries for the user.
I have done so it only use the timeentries for the specific user.

![image](https://user-images.githubusercontent.com/45672692/124452200-78625b00-dd86-11eb-90c5-ee2618812ef9.png)

**Comment by imflitch** [comment]
Support tickets rate are 80 and test are 45.

**Comment by imflitch** [comment]
Also, using datetimeoffsets in almost in of your functions doesn't work, it drops a JSON exception.
I've tried to use it in for example HydratedTimeEntryDtoImpl without it working.

**Comment by Morasiu** [comment]
That's a lot to unpack. 

First. Can you create another Issue and describe what exception is thrown at `HydratedTimeEntryDtoImpl`?

Second, there is a problem with the hourly rate here. Just to confirm:

1. You are sending an hourly rate of 80 to API.
2. API shows that you've sent 0 instead of 80

Right?

**Comment by imflitch** [comment]
Hi.
I can do that later today yea.

No, im getting data from the API/your libary using the function HydratedTimeEntryDtoImpl to get the time entries for a specific user and then i get data like hourly rate.amount but that value is always 0.

**Comment by Morasiu** [comment]
So it's the other way around.

In Clockify you have a value set to 80, but in library, you are getting 0, right?

**Comment by imflitch** [comment]
Yes

**Comment by Morasiu** [comment]
Ok, I'll try to fix that or maybe someone else would o the PR

**Comment by andrewperis** [comment]
I just updated the unit test FindAllHydratedTimeEntriesForUserAsync_ShouldReturnHydratedTimeEntryDtoImplList() to create the test time entry's with a project that has an hourly rate of "1234" which equates to $12.34. Note, Clockify multiplies the rate you enter via the Clockify portal by 100 so as to eliminate the decimal point. What you'll need to do is divide the returned HourlyRate.Amount value by 100 to obtain the actual value you entered.

When I run the updated aforementioned unit test, here's the hourly rate that is returned. Looks okay to me? Given the details above, @imflitch can you try it again and let us know what you're seeing?

`"hourlyRate": {
            "amount": 1234,
            "currency": "USD"
        },`

**Comment by Morasiu** [comment]
Comment if you need more help @imflitch
