### ISSUE TITLE
Option to update Client name?

### ISSUE THREAD

**Issue by diogo1995santo** [Morasiu/Clockify.Net#44]
### Discussed in https://github.com/Morasiu/Clockify.Net/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **diogo1995santo** July  8, 2021</sup>
Hello!

Are there currently any plans to add an option to update a Client name through this client?</div>

**Comment by Morasiu** [comment]
Done in version 1.10.0

Thanks again  @andrewperis
