### ISSUE TITLE
Make it possible to set BaseUrl field

### ISSUE THREAD

**Issue by catfly1** [Morasiu/Clockify.Net#54]
Currently the BaseUrl field is hardcoded and private, meaning its not possible to use this library for self hosted clockify:

https://github.com/Morasiu/Clockify.Net/blob/develop/Clockify.Net/ClockifyClient.cs#L13

**Comment by Morasiu** [comment]
Didn't know you can self-host Clockify. Will do :)

**Comment by Morasiu** [comment]
Added in `1.12.0` :)
