### ISSUE TITLE
GetSummaryReportAsync  is private

### ISSUE THREAD

**Issue by swissbyte** [Morasiu/Clockify.Net#59]
Hi there

Is there a reason, why GetSummaryReportAsync  is made private?

Thanks

**Comment by Morasiu** [comment]
Hey. 

It was not implemented in Clockify at that time. Is it live now?

**Comment by swissbyte** [comment]
Ah ok. Yes, it is live and working now 😊 i tested the api with postman

**Comment by Morasiu** [comment]
Great. I will add it and release new version ;)

**Comment by Morasiu** [comment]
Added in `v.1.14.0` 🎉
