### ISSUE TITLE
DateTimeOffset and ISO 8601 serialization

### ISSUE THREAD

**Issue by chrauscher** [Morasiu/Clockify.Net#6]
Currently the method FindAllTimeEntriesForUserAsync accepts start as parameter (as well as end). the parameter ist a DateTimeOffset that has to be a format mentioned in https://stackoverflow.com/questions/114983/given-a-datetime-object-how-do-i-get-an-iso-8601-date-in-string-format
Otherwise a datetimeoffset as start or end does not work because it only uses tostring to serialize the parameter

**Comment by Morasiu** [comment]
Simple should fix it, right?

```csharp
start.ToString("o");
```

**Comment by chrauscher** [comment]
Yea, that should Do the trick

Hubert Morawski <notifications@github.com> schrieb am Di., 3. März 2020,
19:17:

**Comment by chrauscher** [comment]
start.ToString("o") does not work. It should be start.Value.ToString("o") but hat didn't work as well.

**Comment by chrauscher** [comment]
> start.ToString("o") does not work. It should be start.Value.ToString("o") but hat didn't work as well.

This seems to work: "yyyy-MM-ddTHH:mm:ssZ". Maybe you can give it a try.

**Comment by chrauscher** [comment]
I have tried to create a feature branch but get "Permission to Morasiu/Clockify.Net.git denied to chrauscher."

**Comment by Morasiu** [comment]
I'll check this.

Also, guide in [CONTRIBUTING.md](https://github.com/Morasiu/Clockify.Net/blob/master/Docs/CONTRIBUTING.md) has small bug. I'll fix that soon and inform you.

**Comment by Morasiu** [comment]
Done! You can check new [CONTRIBUTING.md](https://github.com/Morasiu/Clockify.Net/blob/master/Docs/CONTRIBUTING.md)

**Comment by Morasiu** [comment]
Just tested `end.Value.ToString("yyyy-MM-ddThh:mm:ssZ"));`. It works :)
