### ISSUE TITLE
Incompatibility with RestSharp 107.0.0

### ISSUE THREAD

**Issue by tadeucunha** [Morasiu/Clockify.Net#61]
It seems that the new RestSharp 107.0.0 and later does not implement IRestRequest and other Interfaces, according to [https://github.com/restsharp/RestSharp/releases/tag/107.0.0](url)

When building with the new RestSharp package or if there is another RestSharp solution with Clockify.Net, an error occours

The fix seems to be just move from IRestRequest to RestRequest, but further analysis needs to be done.

**Comment by Morasiu** [comment]
Will check it and release a new version :)

**Comment by Morasiu** [comment]
Fixed in 2.0.0!
