### ISSUE TITLE
Unexpected Value Encounted for GetDetailedReportAsync

### ISSUE THREAD

**Issue by StrangeWill** [Morasiu/Clockify.Net#63]
> Unexpected character encountered while parsing value: {. Path 'timeentries[62].tags', line 1, position 34275.

Dropping that JSON into a debugger shows:

```
a.timeentries[62].tags
Array [ {…} ]
​
0: Object { name: "Billed", _id: "62c20bab791b1d5718ea06b0" }
​
length: 1
​
<prototype>: Array []
```

It looks like Clockify.Net expects these items to be strings, however the API appears to be returning a name/ID object, Clockify's documentation doesn't really detail what the summary endpoint expects.

**Comment by Morasiu** [comment]
Fixed in 2.1.1. Thanks!
