### ISSUE TITLE
UserDto.UserSettingDto.LongRunning expects a string but Clockify API returns a bool.

### ISSUE THREAD

**Issue by White7292** [Morasiu/Clockify.Net#8]
First things first - thanks for implementing the Clockify Client, it's much appreciated! That being said, the following property of the `UserSettingsDto` class `public string LongRunning { get; set; }` is of type `string`.

![image](https://user-images.githubusercontent.com/16881776/82360178-fe7edf00-99d6-11ea-8711-badc9361bd31.png)

When the Clockify.me API returns its `UserDto` object which contains the `UserSettingsDto` object, 

![image](https://user-images.githubusercontent.com/16881776/82360468-70efbf00-99d7-11ea-9d40-7b02b46309c4.png)

the content of the `IRestResponse<List<UserDto>>`  has `UserSettingsDto.LongRunning` as the boolean value `false` instead of a string value.

![Screenshot_1](https://user-images.githubusercontent.com/16881776/82361069-5538e880-99d8-11ea-924d-763bfed46763.png)

So when you try to deserialize it with `JsonSerializer.Deserialize`, for example, you get an error.

`System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $[0].settings.longRunning | LineNumber: 0 | BytePositionInLine: 1069.\r\n ---> System.InvalidOperationException: Cannot get the value of a token type 'False' as a string.\r\n   at System.Text.Json.Utf8JsonReader.GetString()\r\n..............`

There's a temporary workaround to this issue, which is to implement a basic boolean JsonConverter that converts a string boolean value false to a string false.

Let me know if you have any questions!

**Comment by Morasiu** [comment]
That's a well-described issue! Really nice job.

I'll look into it. It's probably just simple `type` change to `bool`.

**Comment by Morasiu** [comment]
Fixed in version 1.1.3. Took me a while :)
