### ISSUE TITLE
Discrepancy between TimeEntryDtoImpl class members and response from Clockify.me API.

### ISSUE THREAD

**Issue by White7292** [Morasiu/Clockify.Net#9]
The client library class `TimeEntryDtoImpl` contains a `List<string> TagIds` and a `string TaskId` .

The Clockify.me API returns an `TimeEntryDtoImpl` object that contains a list of tags objects `List<TagDto> TagIds` (or an object very similar to a TagDto) as well as a `TaskDto Task` object (or an object very similar to a TaskDto).

![image](https://user-images.githubusercontent.com/16881776/82389114-4e769980-9a09-11ea-952f-f69ec2bbe8e5.png)

Example Response from `_clockifyClient.FindAllTimeEntriesForUserAsync`:

[
  {
    "id": "<removed_for_privacy>",
    "description": "test description",
    **"tags": [
      {
        "id": "<removed_for_privacy>",
        "name": "Testing",
        "workspaceId": "<removed_for_privacy>",
        "archived": false
      }
    ]**,
    "user": null,
    "billable": false,
    **"task": {
      "id": "<removed_for_privacy>",
      "name": "AAAATESTTASK",
      "projectId": "<removed_for_privacy>",
      "assigneeIds": [],
      "assigneeId": "",
      "estimate": "PT0S",
      "status": "ACTIVE",
      "duration": "PT3H"
    }**,
    "project": {
      "id": "<removed_for_privacy>",
      "name": "AAAATEST PROJECT",
      "hourlyRate": {
        "amount": 0,
        "currency": "USD"
      },
      "clientId": "<removed_for_privacy>",
      "workspaceId": "<removed_for_privacy>",
      "billable": false,
      "memberships": [
        {
          "userId": "<removed_for_privacy>",
          "hourlyRate": null,
          "targetId": "<removed_for_privacy>",
          "membershipType": "PROJECT",
          "membershipStatus": "ACTIVE"
        }
      ],
      "color": "#C106E4",
      "estimate": {
        "estimate": "PT0S",
        "type": "AUTO"
      },
      "archived": false,
      "duration": "PT3H",
      "clientName": "AAAAAATestClient",
      "note": "",
      "template": false,
      "public": false
    },
    "timeInterval": {
      "start": "2020-05-19T10:15:36Z",
      "end": "2020-05-19T13:15:36Z",
      "duration": "PT3H"
    },
    "workspaceId": "<removed_for_privacy>",
    "hourlyRate": null,
    "userId": "<removed_for_privacy>",
    "customFieldValues": null,
    "projectId": "<removed_for_privacy>",
    "isLocked": false
  }
]

The member types for the `TimeEntryDtoImpl` would have to be updated to match the current Clockify.me API.

Let me know if there's anything I can do for ya!

**Comment by Morasiu** [comment]
Another great issue!

That looks like I missed quite a lot of data. I'll fix that.  But in docs, I've found: [TimeEntryImpl](https://clockify.me/developers-api#/definitions/TimeEntryImpl) which looks like this:

```json
{
  "billable": "boolean",
  "description": "string",
  "id": "string",
  "isLocked": "boolean",
  "projectId": "string",
  "tagIds": [
    "string"
  ],
  "taskId": "string",
  "timeInterval": {
    "duration": "string",
    "end": "string (date-time)",
    "start": "string (date-time)"
  },
  "userId": "string",
  "workspaceId": "string"
}
```

Maybe this is a mistake in docs?

**Comment by bennesp** [comment]
I could be wrong but the response posted by @White7292 seems to be to be a response for a hydrated request (see `hydrated: true` in docs)

**Comment by Morasiu** [comment]
Merged :)
